export const SEARCH__PRODUCT_REQUEST = 'SEARCH__PRODUCT_REQUEST';
export const SEARCH__PRODUCT_SUCCESS = 'SEARCH__PRODUCT_SUCCESS';
export const SEARCH__PRODUCT_ERROR = 'SEARCH__PRODUCT_ERROR';

export const CLEAR__ERROR = 'CLEAR__ERROR';

export const SET__FILTERS = 'SET__FILTERS';
